#!/usr/bin/env python3

globals().update(config)

if not logs_directory:
    logger.info("Not keeping logs")
    logs_directory = workingdir
else:
    logger.info(f"Saving logs to {logs_directory}")


include: "rules/agat.smk"
include: "rules/extract_proteins.smk"
include: "rules/utils.smk"


rule target:
    default_target: True
    input:
        rules.check_protein_fasta_file.output,
        rules.agat_sp_statistics.output,
