#!/usr/bin/env python3

globals().update(config)


if not logs_directory:
    logger.info("Not keeping logs")
    logs_directory = workingdir
else:
    logger.info(f"Saving logs to {logs_directory}")


if dev_container:
    container: dev_container


include: "rules/agat.smk"
include: "rules/busco.smk"
include: "rules/extract_proteins.smk"
include: "rules/utils.smk"
include: "rules/omark.smk"


rule target:
    default_target: True
    input:
        rules.agat_sp_statistics.output,
        rules.busco.output,
        rules.omark.output,
